### ISSUE TITLE
[Sounds Mod Incompatibility] Sounds when played on top of players has weird directionality

### ISSUE THREAD

**Issue by deadspidervenom** [FalseMSP/SoundPhysicsPerfected#86]
### Mod Loader

NeoForge

### Mod Version

1.10.5

### Game Version

1.21.1

### What is the bug?

If you have a sound mod that uses a in world audio sound for a non in world sound like the UI. For example "minecraft:block.stone.hit". It will only play in one ear. For me its my right ear.

This is shown in the mod "Sounds". It uses several audio effects from various blocks to add to the immersion, but when your mod is installed they only play from one ear.

**Comment by FalseMSP** [comment]
can't confirm but most issues with the sounds mod is on the sounds mod's side 
the developer of the mod is aware, just hasn't fixed it

**Comment by deadspidervenom** [comment]
> can't confirm but most issues with the sounds mod is on the sounds mod's side the developer of the mod is aware, just hasn't fixed it

bro before saying its someone elses fault and not even trying do your research, they added compatibility with your mod on "Sep 25, 2025" Which unlike the issue you linked who was not hearing sounds at all, i am hearing sounds, but the way you raytrace the audio is causing UI sounds that cant be raytraced to happen in only one ear.

<img width="1920" height="1040" alt="Image" src="https://github.com/user-attachments/assets/570464f0-ae5e-41aa-9cef-121d4791e330" />

**Comment by deadspidervenom** [comment]
The post i mentioned this one in, even the sounds dev does not believe its their fault as they did what you told them to make your two mods compatible.

**Comment by cassiancc** [comment]
> can't confirm but most issues with the sounds mod is on the sounds mod's side the developer of the mod is aware, just hasn't fixed it

New maintainer of Sounds here - I implemented the fix you suggested to make the mod compatible with yours, our sounds now play at the player's position. However, now users of both mods are dealing with mono sounds when pairing my mod with yours, which I believed to be on your end since, again, our sounds are played at the position of the player, making it hard for me to figure out a way to further work around your mod.

**Comment by FalseMSP** [comment]
ah ok, then ig i'll look into it, i was mistaken, sorry

**Comment by FalseMSP** [comment]
https://github.com/FalseMSP/SoundPhysicsPerfected/issues/89
similar to ^

**Comment by deadspidervenom** [comment]
Still having this issue after update, though now its random. Sometimes on load the audio is fine, other times its only in my right ear.

EDIT: Correction, its in both ears, but the left is SUPER quiet

**Comment by deadspidervenom** [comment]
Here is my current modlist, idk if it would help at all.
- [Advanced Chimneys](https://www.curseforge.com/projects/244830) [11\.1\.0\.1]
- [AmbientEnvironment](https://www.curseforge.com/projects/320163) [18\.0\.0\.2]
- [Architectury](https://www.curseforge.com/projects/419699) [13\.0\.8]
- [AstikorCarts Redux](https://www.curseforge.com/projects/916493) [1\.2\.2]
- [Athena](https://modrinth.com/mod/b1ZV3DIJ) [4\.0\.2]
- [Auroras](https://www.curseforge.com/projects/1105290) [1\.6\.2]
- [BBL Core](https://modrinth.com/mod/tfpHINm8) [1\.3\.20]
- [BBL Invisible Lights](https://modrinth.com/mod/UI6gFMOn) [1\.1\.2]
- [BBL Resource Fish](https://www.curseforge.com/projects/1346373) [1\.0\.5]
- [Bad Wither No Cookie Reloaded](https://www.curseforge.com/projects/261251) [3\.20\.3]
- [Better Block Sounds Fork](https://www.curseforge.com/projects/1232054) [1\.21\.1\-1\.0\.0]
- [Blueprint](https://www.curseforge.com/projects/382216) [8\.0\.6]
- [Blur\+](https://www.curseforge.com/projects/393563) [5\.2\.2\+1\.21\.1]
- [Caelus API](https://www.curseforge.com/projects/308989) [7\.0\.1\+1\.21\.1]
- [Carpet: NeoForged](https://modrinth.com/mod/XqqOkvZz) [1\.4\.147\+v1\.0\.7\-250929]
- [Cloth Config v15 API](https://www.curseforge.com/projects/348521) [15\.0\.140]
- [Common Networking](https://www.curseforge.com/projects/806044) [1\.0\.20\-1\.21\.1]
- [Companions\!](https://modrinth.com/mod/ArBFNu9T) [1\.1\.2]
- [Concurrent Chunk Management Engine](https://www.curseforge.com/projects/533097) [0\.3\.0\+alpha\.0\.79\+1\.21\.1]
- [Cool Rain](https://www.curseforge.com/projects/1196599) [1\.1\.0]
- [Curios API](https://www.curseforge.com/projects/309927) [9\.5\.1\+1\.21\.1]
- [Curvy Pipes](https://modrinth.com/mod/Ns4fCzXQ) [1\.13\.4]
- [Deeper Oceans](https://www.curseforge.com/projects/714177) [2\.0\.0]
- [Distant Horizons](https://www.curseforge.com/projects/508933) [2\.3\.4\-b]
- [Distraction Free Recipes \(EMI\)](https://modrinth.com/mod/gbJLUhZP) [1\.2\.1]
- [EMI](https://modrinth.com/mod/fRiHVvU7) [1\.1\.22\+1\.21\.1\+neoforge]
- [EMI Enchanting](https://modrinth.com/mod/wbWoo11W) [0\.1\.2\+1\.21\+neoforge]
- [EMI Loot](https://modrinth.com/mod/qbbO7Jns) [0\.7\.6\+1\.21\+neoforge]
- [EMI Ores](https://modrinth.com/mod/sG4TqDb8) [1\.2\+1\.21\.1\+neoforge]
- [EMI Professions \(EMIP\)](https://modrinth.com/mod/LGVihYcz) [1\.0\.3]
- [EMI\+\+](https://modrinth.com/mod/AWMWYMwC) [1\.2\.3]
- [EMIffect](https://modrinth.com/mod/705gWllI) [2\.1\.6\+mc1\.21\.1]
- [Effortless Building](https://www.curseforge.com/projects/302113) [3\.10]
- [Ender\-Rift](https://www.curseforge.com/projects/233780) [2\.9\.2]
- [Extra Mod Integrations](https://modrinth.com/mod/bpRHnWUb) [1\.0\.3\+1\.21\.1]
- [ForgeEndertech](https://www.curseforge.com/projects/244844) [12\.1\.0\.0]
- [Forgified Fabric API](https://www.curseforge.com/projects/889079) [0\.115\.6\+2\.1\.3\+1\.21\.1]
- [Fzzy Config](https://modrinth.com/mod/hYykXjDp) [0\.7\.2\+1\.21\+neoforge]
- [GeckoLib 4](https://modrinth.com/mod/8BmcQJ2H) [4\.8\.2]
- [GlitchCore](https://www.curseforge.com/projects/955399) [2\.1\.0\.0]
- [GuideME](https://modrinth.com/mod/Ck4E7v7R) [21\.1\.14]
- [Guidebook](https://www.curseforge.com/projects/253874) [3\.10\.1]
- [Icarus](https://www.curseforge.com/projects/428151) [4\.5\.1]
- [Immersive Snow](https://www.curseforge.com/projects/1058082) [1\.4\.0]
- [ImmersiveUI](https://www.curseforge.com/projects/1021685) [0\.3\.3]
- [Just Enough Items](https://www.curseforge.com/projects/238222) [19\.25\.0\.322]
- [Just Hammers](https://modrinth.com/mod/edU0NbZZ) [21\.1\.1]
- [Kiwi Library](https://www.curseforge.com/projects/303657) [15\.7\.3\+neoforge]
- [Knight Lib](https://modrinth.com/mod/hAnl9nbm) [1\.3\.0]
- [Kotlin for Forge](https://modrinth.com/mod/ordsPcFz) [pp2cY80Q]
- [Lithostitched](https://www.curseforge.com/projects/936015) [1\.5\.0\-beta6]
- [M\.R\.U](https://www.curseforge.com/projects/669659) [1\.0\.19\+LTS\+1\.21\.1\+neoforge]
- [Map Atlases](https://modrinth.com/mod/4hwXMFif) [1\.21\-6\.3\.6]
- [Mermod](https://www.curseforge.com/projects/709092) [3\.3\.2]
- [MidnightLib](https://www.curseforge.com/projects/488090) [1\.7\.5]
- [Mine Treasure](https://www.curseforge.com/projects/664221) [1\.4\.6]
- [Modonomicon](https://modrinth.com/mod/692GClaE) [1\.115\.1]
- [Moonlight Lib](https://www.curseforge.com/projects/499980) [1\.21\-2\.23\.11]
- [MultiStorage](https://www.curseforge.com/projects/244864) [1\.21\.1\-1\.0]
- [Multipart Machines: Farming](https://www.curseforge.com/projects/867296) [2\.1]
- [Multipart Machines: Grinding](https://www.curseforge.com/projects/859298) [2\.1]
- [Multipart Machines: Mining](https://www.curseforge.com/projects/962841) [1\.3]
- [Multipart Machines: Storage](https://www.curseforge.com/projects/916819) [2\.0]
- [Neo Enchant\+](https://modrinth.com/mod/BynmO8IO) [5\.10]
- [OctoLib](https://www.curseforge.com/projects/916747) [0\.6\.0\.4]
- [Particular](https://www.curseforge.com/projects/1219053) [1\.1\.6]
- [Pastel](https://modrinth.com/mod/5lr6fnw0) [1\.1\.4\.1]
- [Patchouli](https://modrinth.com/mod/nU0bVIaL) [1\.21\.1\-92\-NEOFORGE]
- [Pehkui](https://www.curseforge.com/projects/319596) [3\.8\.3\+1\.21\-neoforge]
- [Platform](https://www.curseforge.com/projects/997634) [1\.2\.10\.2]
- [Powah](https://www.curseforge.com/projects/633483) [6\.2\.6]
- [Prefab](https://modrinth.com/mod/pTJ1ZloG) [1\.0\.4]
- [Psi](https://modrinth.com/mod/pOeA0exL) [2\.0\.0]
- [Psionic Relics](https://www.curseforge.com/projects/984059) [1\.21\.1\-1\.0\.1]
- [Rainbows](https://www.curseforge.com/projects/1121832) [1\.5]
- [Random Mob Sizes](https://www.curseforge.com/projects/555230) [1\.21\.1\-2\.2\.2]
- [Redden's Stone Lanterns](https://www.curseforge.com/projects/965820) [1\.0\.3]
- [Resourcefulconfig](https://www.curseforge.com/projects/714059) [3\.0\.11]
- [RoadArchitect](https://www.curseforge.com/projects/1326434) [1\.5\.0]
- [Scriptor Magicae](https://www.curseforge.com/projects/817436) [1\.4\.13]
- [Sculk Transporting](https://modrinth.com/mod/G2cuXzjx) [1\.2\.2]
- [Seamless Loading Screen](https://www.curseforge.com/projects/429926) [2\.2\.1\+1\.21]
- [Serene Seasons](https://www.curseforge.com/projects/291874) [10\.1\.0\.3]
- [ShetiPhianCore](https://www.curseforge.com/projects/71738) [1\.21\.1\-1\.1]
- [Simple Clouds](https://www.curseforge.com/projects/1121215) [0\.7\.3\+1\.21\.1]
- [Sinytra Connector](https://www.curseforge.com/projects/890127) [7046486]
- [Slimeasier](https://modrinth.com/mod/CvbeYto3) [1\.3]
- [Snow\! Real Magic\!](https://www.curseforge.com/projects/308663) [12\.1\.2\+neoforge]
- [Sound Physics Perfected](https://modrinth.com/mod/KS6Hbu9Z) [1\.11\.0]
- [Sounds](https://www.curseforge.com/projects/925889) [2\.4\.15\+lts\+1\.21\.1\+neoforge]
- [Sparkweave Engine](https://www.curseforge.com/projects/911456) [0\.510\.0]
- [Stellar View](https://www.curseforge.com/projects/865273) [0\.5\.1]
- [Storage Labels](https://www.curseforge.com/projects/688223) [1\.21\-2\.0\.1]
- [Talismans](https://www.curseforge.com/projects/1235496) [1\.2]
- [Titanium](https://modrinth.com/mod/1Ro7m06l) [4\.0\.40]
- [Transfer Labels](https://modrinth.com/mod/hRrzpz5p) [0\.1\.7]
- [Transprot](https://modrinth.com/mod/zczCwRKj) [2\.0\.1]
- [TxniLib](https://modrinth.com/mod/vBbPDuOs) [1\.0\.24]
- [Unfocused](https://www.curseforge.com/projects/1178682) [0\.2\.2\-1\.21\.1]
- [Upgrade Aquatic](https://www.curseforge.com/projects/326895) [7\.0\.0]
- [VanillaBackport](https://www.curseforge.com/projects/417430) [1\.1\.4\.3]
- [Via Romana](https://www.curseforge.com/projects/1026508) [2\.0\.1\+1\.21\.1\-neoforge]
- [VisualOverhaul](https://www.curseforge.com/projects/432008) [5\.2\.1]
- [Visuality: Reforged](https://www.curseforge.com/projects/704256) [2\.1\.0]
- [World Icon Updater](https://www.curseforge.com/projects/1301553) [1\.0\.1]
- [YetAnotherConfigLib](https://www.curseforge.com/projects/667299) [3\.8\.0\+1\.21\.1\-neoforge]
- [oωo](https://modrinth.com/mod/ccKDOlHs) [0\.12\.15\.5\-beta\.1\+1\.21]

**Comment by FalseMSP** [comment]
honestly no idea then, will leave open but i don't really know what is causing it

**Comment by jezmeista** [comment]
Second this on 1.11.1-hotfix, sometimes it will be stuck on the right ear, and rarely it's stuck on the left ear.  Unfortunate that the sounds perfected mod isn't compatible with the sounds mod at the moment, otherwise the mod is amazing

**Comment by FalseMSP** [comment]
its still on my mod's end, will continue to look into

**Comment by FalseMSP** [comment]
<img width="73" height="181" alt="Image" src="https://github.com/user-attachments/assets/7d4a316f-7f43-41b5-b408-15da54b6b854" /> 1.11.2 will fix it (mostly, there is still slight panning, but idk if i can fix it atp)

**Comment by deadspidervenom** [comment]
> <img alt="Image" width="73" height="181" src="https://private-user-images.githubusercontent.com/55561022/499489236-7d4a316f-7f43-41b5-b408-15da54b6b854.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAyNTIzNzQsIm5iZiI6MTc2MDI1MjA3NCwicGF0aCI6Ii81NTU2MTAyMi80OTk0ODkyMzYtN2Q0YTMxNmYtN2Y0My00MWI1LWI0MDgtMTVkYTU0YjZiODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDEyVDA2NTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiY2M4NjZkZDFhYWRlZmM5NDRjMWY2OGQ0OTVmZWMzZjZjMzY1ZmJiNTczZWZhNDI1YTg3MjBjYjRhOGNmMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gxLQVZWDBFqzSm-pyopinuLzET-UCtlz7wnUCgIp0ZU"> 1.11.2 will fix it (mostly, there is still slight panning, but idk if i can fix it atp)

was thinking, couldn't you make it so that any sound played at like 0, 0, 0 of the player (so the very center of the player) gets forced into mono audio? 

I thought about this because my amp for my mic has stereo hook ups so i can do 2 audio inputs, so i have to make my mic mono when using it else my voice end up in only one ear.

**Comment by FalseMSP** [comment]
> > <img alt="Image" width="73" height="181" src="https://private-user-images.githubusercontent.com/55561022/499489236-7d4a316f-7f43-41b5-b408-15da54b6b854.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAyNTIzNzQsIm5iZiI6MTc2MDI1MjA3NCwicGF0aCI6Ii81NTU2MTAyMi80OTk0ODkyMzYtN2Q0YTMxNmYtN2Y0My00MWI1LWI0MDgtMTVkYTU0YjZiODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDEyVDA2NTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiY2M4NjZkZDFhYWRlZmM5NDRjMWY2OGQ0OTVmZWMzZjZjMzY1ZmJiNTczZWZhNDI1YTg3MjBjYjRhOGNmMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gxLQVZWDBFqzSm-pyopinuLzET-UCtlz7wnUCgIp0ZU"> 1.11.2 will fix it (mostly, there is still slight panning, but idk if i can fix it atp)
> 
> was thinking, couldn't you make it so that any sound played at like 0, 0, 0 of the player (so the very center of the player) gets forced into mono audio?
> 
> I thought about this because my amp for my mic has stereo hook ups so i can do 2 audio inputs, so i have to make my mic mono when using it else my voice end up in only one ear.

yes, if i knew how to i would. afaik the only way to do that is by setting the attenuation mode to NONE, in which case my mod doesn't even process it.

also if someone can confirm this is fixed other than me (bc i really haven't been able to recreate to much success) i can close the issue.

**Comment by nijahplays** [comment]
Getting this issue with [this](https://modrinth.com/modpack/nijahplays-personal-pack) modpack when replacing Sound Physics with this mod when doing anything with UI elements that include text chat. Using the latest version of this mod (1.11.3)

**Comment by deadspidervenom** [comment]
> > > <img alt="Image" width="73" height="181" src="https://private-user-images.githubusercontent.com/55561022/499489236-7d4a316f-7f43-41b5-b408-15da54b6b854.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAyNTIzNzQsIm5iZiI6MTc2MDI1MjA3NCwicGF0aCI6Ii81NTU2MTAyMi80OTk0ODkyMzYtN2Q0YTMxNmYtN2Y0My00MWI1LWI0MDgtMTVkYTU0YjZiODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDEyVDA2NTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiY2M4NjZkZDFhYWRlZmM5NDRjMWY2OGQ0OTVmZWMzZjZjMzY1ZmJiNTczZWZhNDI1YTg3MjBjYjRhOGNmMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gxLQVZWDBFqzSm-pyopinuLzET-UCtlz7wnUCgIp0ZU"> 1.11.2 will fix it (mostly, there is still slight panning, but idk if i can fix it atp)
> > 
> > 
> > was thinking, couldn't you make it so that any sound played at like 0, 0, 0 of the player (so the very center of the player) gets forced into mono audio?
> > I thought about this because my amp for my mic has stereo hook ups so i can do 2 audio inputs, so i have to make my mic mono when using it else my voice end up in only one ear.
> 
> yes, if i knew how to i would. afaik the only way to do that is by setting the attenuation mode to NONE, in which case my mod doesn't even process it.
> 
> also if someone can confirm this is fixed other than me (bc i really haven't been able to recreate to much success) i can close the issue.

no change with the updated version for me. Than why not do that? Your mod is not needed for UI sounds only sounds in the world right?

**Comment by FalseMSP** [comment]
> Than why not do that? Your mod is not needed for UI sounds only sounds in the world right?

in that case that would be on the Sounds developer side.
But yes, got another bump from @swiyss on discord "When I juggle through inventory, it's a fixed panning left or right sound depending on how close I am to spawn. "
will continue to look into it.

**Comment by AdventureBow** [comment]
I tested this with only Sounds and SPP and their dependencies, I am receiving audio from both channels, but dominantly form the right as if the sound were coming from there, and barely hear it if I take off the right headphone.

**Comment by FalseMSP** [comment]
https://github.com/IMB11-Mods/Sounds/pull/217
the end of the sounds mod saga (maybe)
(i like how it could've all been fixed by a single line of code if it actually is this simple...)

**Comment by nijahplays** [comment]
Is there any downside of setting the attenuation to none?

**Comment by deadspidervenom** [comment]
> Is there any downside of setting the attenuation to none?

for ui sounds? i'd assume not. Since their not in the world, they only need mono audio.

**Comment by FalseMSP** [comment]
ITS FINALLY MERGED IN!!
ggs
finally will stop hearing about this!
